datakaveri/iudx-file-server

.github/workflows/build.yml
README.md
pom.xml
src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java
src/main/java/iudx/file/server/authenticator/authorization/Api.java
src/main/java/iudx/file/server/authenticator/authorization/AuthorizationContextFactory.java
src/main/java/iudx/file/server/authenticator/authorization/AuthorizationRequest.java
src/main/java/iudx/file/server/authenticator/authorization/AuthorizationStrategy.java
src/main/java/iudx/file/server/authenticator/authorization/ConsumerAuthStrategy.java
src/main/java/iudx/file/server/authenticator/authorization/DelegateAuthStrategy.java
src/main/java/iudx/file/server/authenticator/authorization/JwtAuthorization.java
src/main/java/iudx/file/server/authenticator/authorization/Method.java
src/main/java/iudx/file/server/authenticator/authorization/ProviderAuthStrategy.java
src/main/java/iudx/file/server/authenticator/utilities/Constants.java
src/main/java/iudx/file/server/authenticator/utilities/JwtData.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java
src/test/java/iudx/file/server/configuration/Configuration.java

Feature Jwt token Impl

---

docker-compose.test.yml
src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/handlers/ValidationsHandler.java
src/main/java/iudx/file/server/apiserver/service/impl/LocalStorageFileServiceImpl.java
src/main/java/iudx/file/server/auditing/AuditingServiceImpl.java
src/main/java/iudx/file/server/auditing/util/QueryBuilder.java
src/main/java/iudx/file/server/authenticator/AuthenticationVerticle.java
src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java
src/main/java/iudx/file/server/database/elasticdb/DatabaseServiceImpl.java
src/main/java/iudx/file/server/database/elasticdb/elastic/ElasticClient.java
src/main/java/iudx/file/server/databroker/DataBrokerVerticle.java
src/main/resources/log4j2.xml
src/test/java/iudx/file/server/apiserver/service/LocalFileStorageTest.java
src/test/java/iudx/file/server/auditing/AuditingServiceTest.java

- remove some sensitive debug logs
- convert non-essential info level to debug
- needed for only specific/detailed debugging
- non-meaningful logs
- have checked all info, error, warn level logs. There is no other sensitive info logs. except for this, not sure if the sub field in jwt is very sensitive or not https://github.com/datakaveri/iudx-file-server/blob/7e94058e3387185aa131531292f4f4769f46b35b/src/main/java/iudx/file/server/databroker/DataBrokerVerticle.java#L126

Remove sensitive logs, irrelevant info logs

---

src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/utilities/Constants.java
src/main/java/iudx/file/server/apiserver/utilities/HttpStatusCode.java
src/main/java/iudx/file/server/apiserver/validations/ValidationHandlerFactory.java
src/main/java/iudx/file/server/apiserver/validations/types/StorageTypeValidator.java
src/main/java/iudx/file/server/apiserver/validations/types/StorageURLValidator.java
src/main/java/iudx/file/server/database/elasticdb/elastic/ElasticClient.java
src/test/java/iudx/file/server/apiserver/validations/ValidationHandlerFactoryTest.java
src/test/resources/iudx-file-server-api.Release-v3.5.postman_collection.json

[surefire-report.pdf](https://github.com/datakaveri/iudx-file-server/files/7956110/surefire-report.pdf)

external storage

---

Jenkinsfile
docker-compose.test.yml
src/test/resources/iudx-file-server-api.Release-v3.5.postman_collection.json

- Refactored CI code.
- Re-enabled SSL for Integration tests.

Jenkins CI improvements

---

Jenkinsfile

fix for stale test reports that might cause issue with PR builds.

Jenkins CI update: Added cleanup of unit test reports after stage completion

---

README.md
docker-compose.yml
docker/build-push.sh
docker/depl.dockerfile
docker/dev.dockerfile
example-configs/config-depl.json
example-configs/config-dev.json
example-configs/config-test.json

@abhi4578  plz check this PR, if any change is required, plz let me know.

non-root-img for file server

---

src/test/java/iudx/file/server/apiserver/handler/ValidationFailureHandlerTest.java
src/test/java/iudx/file/server/apiserver/validations/types/StorageURLValidatorTest.java
src/test/java/iudx/file/server/common/WebClientFactoryTest.java

Rebased the commits present here : https://github.com/datakaveri/iudx-file-server/pull/70

Rebased the previous commits

---

src/test/java/iudx/file/server/apiserver/handler/ValidationFailureHandlerTest.java
src/test/java/iudx/file/server/apiserver/validations/types/StorageURLValidatorTest.java
src/test/java/iudx/file/server/common/CatalogueServiceTest.java
src/test/java/iudx/file/server/common/WebClientFactoryTest.java

Added test cases in CatalogueServiceTest

Add test cases in catalogue service test

---

src/test/java/iudx/file/server/auditing/AuditingServiceTest.java

Added remaining test cases for the class AuditingServiceImpl

Add test cases in AuditingServiceTest

---

src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java

Changed JwtAuthenticationServiceImpl class by removing the final keyword from `WebClient catWebClient`

Add test cases in JwtAuthServiceTest.java

---

src/test/java/iudx/file/server/apiserver/validations/types/StorageTypeValidatorTest.java

Added test cases for class StorageTypeValidator.java

Add StorageTypeValidatorTest

---

src/test/java/iudx/file/server/apiserver/exceptions/DxRuntimeExceptionTest.java
src/test/java/iudx/file/server/apiserver/handler/AuthHandlerTest.java
src/test/java/iudx/file/server/apiserver/response/ResponseTypeTest.java
src/test/java/iudx/file/server/cache/CacheServiceTest.java
src/test/java/iudx/file/server/common/ResponseTest.java

Added test cases for class 
---
1. AuthHandler
2. DxRuntimeException
3. Response
4. ResponseType
5. CacheServiceImpl

Add test cases

---

src/main/java/iudx/file/server/authenticator/utilities/Constants.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java
src/test/resources/FS.postman_environment.json
src/test/resources/iudx-file-server-api.Release-v3.5.postman_collection.json

- Updated postman collection and environment files
- Modified list and search APIs to use open and secure tokens as per the resource openness <open resource/resource groups shall use an open token and secure resource/resource groups will expect secure tokens>

Bug Fix: CI pipeline

---

Jenkinsfile
pom.xml
src/main/java/iudx/file/server/apiserver/handlers/AuthHandler.java
src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java
src/main/java/iudx/file/server/authenticator/utilities/Constants.java
src/main/java/iudx/file/server/cache/cacheImpl/RevokedClientCache.java
src/test/java/iudx/file/server/apiserver/handler/AuthHandlerTest.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java
src/test/resources/FS.postman_environment.json
src/test/resources/iudx-file-server-api.Release-v3.5.postman_collection.json

- Updated postgressql version 42.3.3 -> 42.4.0
- included SCRAM256 lib for postgres.

pg migration to latest

---

src/main/java/iudx/file/server/apiserver/handlers/AuthHandler.java
src/test/resources/iudx-file-server-api.Release-v3.5.postman_collection.json

- deleting a file is only allowed for delegate/provider role.
closes #88

delete through secure token bug

---

example-configs/config-depl.json
example-configs/config-dev.json
example-configs/config-test.json
src/main/java/iudx/file/server/database/elasticdb/DatabaseServiceImpl.java
src/test/java/iudx/file/server/database/DatabaseServiceTest.java
src/test/java/iudx/file/server/database/elastic/ElasticQueryGeneratorTest.java

All file server metadata will be saved in a single index

using single index for all metadata with id

---

docker/depl.dockerfile
docker/dev.dockerfile

- create proper upload and temp dir

Dockerfile corrections

---

docs/openapi.yaml
src/main/java/iudx/file/server/apiserver/utilities/Constants.java
src/main/java/iudx/file/server/apiserver/validations/RequestValidator.java
src/test/resources/iudx-file-server-api.Release-v4.0.postman_collection.json

Duplicate of PR #103, for 4.0.0 branch

date param [lowercase]

---

src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/utilities/Constants.java
src/main/java/iudx/file/server/auditing/AuditingServiceImpl.java
src/main/java/iudx/file/server/auditing/AuditingVerticle.java
src/main/java/iudx/file/server/auditing/util/Constants.java
src/main/java/iudx/file/server/auditing/util/QueryBuilder.java
src/main/java/iudx/file/server/databroker/DataBrokerService.java
src/main/java/iudx/file/server/databroker/DataBrokerServiceImpl.java
src/main/java/iudx/file/server/databroker/DataBrokerVerticle.java
src/test/java/iudx/file/server/auditing/AuditingServiceTest.java
src/test/java/iudx/file/server/databroker/DataBrokerServiceImplTest.java

-- Execute Write Code
-- Test Cases
-- DataBrokerImpl publishmessage
-- Databroker Test Cases

Auditing executeWrite

---

example-configs/config-dev.json
example-configs/config-test.json
src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/authenticator/AuthenticationVerticle.java
src/main/java/iudx/file/server/authenticator/authorization/AuthorizationContextFactory.java
src/main/java/iudx/file/server/authenticator/authorization/ConsumerAuthStrategy.java
src/main/java/iudx/file/server/authenticator/authorization/DelegateAuthStrategy.java
src/main/java/iudx/file/server/authenticator/authorization/ProviderAuthStrategy.java
src/main/java/iudx/file/server/common/Api.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java

Updated the following classes :
-  FileServerVerticle.java
-  AuthenticationVerticle.java
-  AuthorizationContextFactory.java
-  ConsumerAuthStrategy.java
-  DelegateAuthStrategy.java
-  ProviderAuthStrategy.java
-  common/Api.java
-  JwtAuthServiceTest.java

Make classes singleton

---

docs/apidoc.html
docs/openapi.yaml
src/main/java/iudx/file/server/apiserver/service/impl/LocalStorageFileServiceImpl.java
src/test/resources/FS.postman_environment.json
src/test/resources/README.md
src/test/resources/iudx-file-server-api.Release-v4.0.postman_collection.json

Changes done:
1. Added README.md for the configurable base path
2. Changed file-test.iudx.io to file.iudx.io in Postman environment
3. Made configurable base path in postman collection
4. Added Logo in the docs and refactored the API doc
5. Replaced the occurrences of IUDX with DX or DX(Data Exchange)
6. Added configuration section in API docs
7. Removed the base path being appended to the API in the docs
8. Changed the /download, /delete APIs by replacing the `file-id` given in the path params to query params   
9. Replaced results in the response schema with an array of fields and not the specific field
10. Prefixed the status code with type for the APIs in Postman collection
11. Updated LocalStorageFileServiceImpl to check if the directory path has "/" in the end and append if not …

Update api docs

---

docs/apidoc.html
docs/openapi.yaml
src/main/java/iudx/file/server/apiserver/service/impl/LocalStorageFileServiceImpl.java

Changes done:
- Updated the results format
- Removed the logo as it was not visible after the deployment

Refactor api docs

---

docs/openapi.yaml
src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/handlers/ValidationsHandler.java
src/main/java/iudx/file/server/apiserver/response/RestResponse.java
src/test/resources/iudx-file-server-api.Release-v4.5.0.postman_collection.json

* fixed response format mismatch for /upload  and /delete end point.
* postman collection updated for new response format.
* openapi docs updated accordingly.
* fileId .txt extension issue fixed for delete end point. 
resolve #129

 response format

---

src/main/java/iudx/file/server/authenticator/utilities/JwtData.java

* fixed null token issue in JwtAuthenticationServiceImpl

null token

---

Jenkinsfile
src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/handlers/ValidationFailureHandler.java
src/main/java/iudx/file/server/apiserver/utilities/Constants.java
src/main/java/iudx/file/server/apiserver/validations/types/FileIdTypeValidator.java
src/main/java/iudx/file/server/apiserver/validations/types/IdTypeValidator.java
src/main/java/iudx/file/server/auditing/AuditingServiceImpl.java
src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java
src/main/java/iudx/file/server/common/Constants.java
src/main/java/iudx/file/server/common/service/CatalogueService.java
src/main/java/iudx/file/server/common/service/impl/CatalogueServiceImpl.java
src/main/java/iudx/file/server/database/elasticdb/DatabaseServiceImpl.java
src/test/java/iudx/file/server/apiserver/handler/ValidationsHandlerTest.java
src/test/java/iudx/file/server/apiserver/validations/types/FileIdTypeValidatorTest.java
src/test/java/iudx/file/server/apiserver/validations/types/IDTypeValidatorTest.java
src/test/java/iudx/file/server/auditing/util/ResponseBuilderTest.java
src/test/java/iudx/file/server/authenticator/JwtAuthServiceTest.java
src/test/java/iudx/file/server/common/CatalogueServiceTest.java
src/test/resources/iudx-file-server-api.Release-v5.0.0.postman_collection.json

* UUID type id support.
Note :

Id related changes

---

src/main/java/iudx/file/server/apiserver/FileServerVerticle.java

* change file directory into group level

modify file directory

---

docs/openapi.yaml
src/main/java/iudx/file/server/authenticator/JwtAuthenticationServiceImpl.java

* skip id check for upload & delete service.
* modify api docs according to new id changes.

skip id check

---

src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/auditing/util/Constants.java

updated auditing message

---

Jenkinsfile
README.md
docker-compose.test.yml

- Updated image tag to `5.0.0-{commit-hash}`
- Archived configs to 5.0.0 dir 
- Updated git badge links

[5.0.0] Jenkins CI: Updates for 5.0.0 pipeline

---

src/test/java/iudx/file/server/apiserver/integrationTests/RestAssuredConfiguration.java

removed logger

---

src/test/java/iudx/file/server/apiserver/integrationTests/RestAssuredConfiguration.java
src/test/java/iudx/file/server/authenticator/TokenSetup.java

- made audience value configurable.

restAssured configuration upadate

---

.github/workflows/docker-image-stable.yml
.github/workflows/docker-image.yml
Jenkinsfile

- Separated docker image workflow file based on branch, master, and release branch
https://github.com/datakaveri/iudx-deployment/issues/721

Separated docker image workflow file

---

src/main/java/iudx/file/server/authenticator/AuthenticationVerticle.java
src/main/java/iudx/file/server/common/Constants.java

Added JWT Leeway time in Authentication Verticle

jwt-leeway-added

---

src/main/java/iudx/file/server/authenticator/AuthenticationVerticle.java
src/main/java/iudx/file/server/common/Constants.java

JWT Leeway added in Authentication Verticle

jwt-leeway-added-5.5.0

---

pom.xml
src/main/java/iudx/file/server/apiserver/FileServerVerticle.java
src/main/java/iudx/file/server/apiserver/service/FileService.java
src/main/java/iudx/file/server/apiserver/service/impl/LocalStorageFileServiceImpl.java
src/main/java/iudx/file/server/apiserver/utilities/Constants.java
src/main/java/iudx/file/server/authenticator/authorization/ConsumerAuthStrategy.java
src/main/java/iudx/file/server/common/Api.java

This PR has addition of two new endpoints for upload and download of GTFS data in Protobuf format.

added gtfs endpoints

---

Jenkinsfile
docker-compose.test.yml
docker/test.dockerfile

1.added conditional statement for checking necessary file changes
2.added trivy stages
3.removed unnecessary statements
4.optimized unit tests

[DI-22] [Jenkins CI]: Add stage optimization changes and trivy stages
